[package]
name = "FlowForge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.26.2"
egui = "0.26.2"
egui-winit = "0.26.2"
egui_glow = "0.26.2"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.6", features = ["v4"] }
serde_json = "1.0"