[package]
name = "FlowForge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add the missing egui-winit dependency, which the compiler suggested.
egui-winit = "0.26"
actix-web = "4"